spring:
  shardingsphere:
    datasource:
      ds:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds
    sharding:
      binding-tables: t_order,t_order_item
      broadcast-tables: t_address
      tables:
        t_order:
          actual-data-nodes: ds.t_order_$->{0..1}
          key-generator:
            column: order_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: t_order_$->{order_id % 2}
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: ds.t_order_item_$->{0..1}
          key-generator:
            column: order_item_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: t_order_item_$->{order_id % 2}
              sharding-column: order_id

